# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_insulin', models.IntegerField(default=0)),
                ('low_tyroids', models.IntegerField(default=0)),
                ('high_cortisol', models.IntegerField(default=0)),
                ('low_cortisal', models.IntegerField(default=0)),
                ('high_androgen', models.IntegerField(default=0)),
                ('low_androgen', models.IntegerField(default=0)),
                ('estrogen_dominace', models.IntegerField(default=0)),
                ('estrogen_progesterone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.Question'),
        ),
    ]
